[package]
name = "pr-terminal"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false
description = "Penguin Redis — pr-terminal"

[lints]
workspace = true

[[bin]]
name = "pr-terminal-demo"
path = "src/bin/demo.rs"

[dependencies]
crossterm = { workspace = true }
pr-render = { path = "../pr-render" }
pr-repl = { path = "../pr-repl" }
thiserror = { workspace = true }

[dev-dependencies]
unicode-width = { workspace = true }
portable-pty = "0.9"
pty-harness = { path = "../../xtask/pty-harness" }
