[package]
name = "pr-transport"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false
description = "Penguin Redis — pr-transport"

[lints]
workspace = true

[dependencies]
bytes = { workspace = true }
thiserror = { workspace = true }
pr-protocol = { path = "../pr-protocol" }
