//! Stamp and verify pinned catalog snapshots (V-F01).
//!
//! The digest is computed here, in Rust, with the same blake3 implementation that hashes
//! approvals (ADR-009), so the project has exactly one hashing path. The capture script
//! writes the JSON; this writes the fingerprint a reviewer's signature effectively covers.

use std::path::Path;

/// Compute and write `<path>.blake3`. Refuses a file that does not parse or is not canonical,
/// because stamping an unreadable snapshot would certify nothing.
///
/// # Errors
/// Returns a message describing why the file could not be stamped.
pub fn stamp(path: &Path) -> Result<String, String> {
    let bytes = std::fs::read(path).map_err(|e| format!("{}: {e}", path.display()))?;
    pr_catalog::snapshot::parse_unverified(&bytes)
        .map_err(|e| format!("{}: {e}", path.display()))?;
    let d = pr_catalog::snapshot::digest(&bytes);
    let side = sidecar(path);
    std::fs::write(&side, format!("{d}\n")).map_err(|e| format!("{}: {e}", side.display()))?;
    Ok(d)
}

/// Verify a snapshot against its sidecar and report what it contains.
///
/// # Errors
/// Returns a message if the sidecar is missing or the snapshot does not load.
pub fn verify(path: &Path) -> Result<String, String> {
    let bytes = std::fs::read(path).map_err(|e| format!("{}: {e}", path.display()))?;
    let side = sidecar(path);
    let expected = std::fs::read_to_string(&side)
        .map_err(|e| format!("{} (run `xtask catalog-stamp`): {e}", side.display()))?;
    let snap = pr_catalog::snapshot::load(&bytes, &expected)
        .map_err(|e| format!("{}: {e}", path.display()))?;
    Ok(format!(
        "{} {} ({}) {} commands, captured {} from {}",
        snap.provenance.family,
        snap.provenance.line,
        snap.provenance.server_version,
        snap.commands.len(),
        snap.provenance.captured_utc,
        snap.provenance.image,
    ))
}

fn sidecar(path: &Path) -> std::path::PathBuf {
    let mut s = path.as_os_str().to_os_string();
    s.push(".blake3");
    std::path::PathBuf::from(s)
}

/// Write the Redis/Valkey difference list to a fixture directory (V-I02).
///
/// Two files, both deterministic:
///
/// - `diff.md` — what a person reads, grouped by the kind of difference and by why it matters
/// - `summary.txt` — the counts, which is what a CI gate compares
///
/// The fixture is regenerated and diffed in CI, so a snapshot refresh that silently changes
/// the divergence shows up as a failing job rather than as a surprise in Phase 2.
///
/// # Errors
/// A message describing which file could not be written.
pub fn write_diff(dir: &Path) -> Result<String, String> {
    use pr_catalog::diff::diff;

    let redis = pr_catalog::embedded::redis();
    let valkey = pr_catalog::embedded::valkey();
    let d = diff(redis, valkey);

    std::fs::create_dir_all(dir).map_err(|e| format!("{}: {e}", dir.display()))?;
    let md = render_markdown(&d, redis.len(), valkey.len());
    std::fs::write(dir.join("diff.md"), &md)
        .map_err(|e| format!("{}: {e}", dir.join("diff.md").display()))?;

    let summary = format!(
        "redis_commands {}\nvalkey_commands {}\nidentical {}\nredis_only {}\nvalkey_only {}\nargument_differences {}\nsince_differences {}\neffect_differences {}\n",
        redis.len(),
        valkey.len(),
        d.identical,
        d.redis_only.len(),
        d.valkey_only.len(),
        d.arguments.len(),
        d.since.len(),
        d.effects.len(),
    );
    std::fs::write(dir.join("summary.txt"), &summary)
        .map_err(|e| format!("{}: {e}", dir.join("summary.txt").display()))?;

    Ok(format!(
        "{} difference(s) written to {}",
        d.total(),
        dir.display()
    ))
}

fn render_markdown(d: &pr_catalog::diff::CatalogDiff, redis_n: usize, valkey_n: usize) -> String {
    use std::fmt::Write as _;
    let mut s = String::new();
    s.push_str("# Redis vs Valkey — catalog difference list\n\n");
    s.push_str(
        "Generated by `cargo run -p xtask -- catalog-diff`. Do not edit: CI regenerates this \n\
         and fails on a difference, so an edit here is a change nobody reviewed.\n\n\
         Each section says what ignoring it would break, because the four kinds are not \n\
         equally dangerous.\n\n",
    );
    let _ = writeln!(
        s,
        "| | count |\n|---|---|\n| Redis commands | {redis_n} |\n| Valkey commands | {valkey_n} |\n\
         | identical in both | {} |\n| Redis only | {} |\n| Valkey only | {} |\n\
         | argument differences | {} |\n| `since` differences | {} |\n| **effect differences** | {} |\n",
        d.identical,
        d.redis_only.len(),
        d.valkey_only.len(),
        d.arguments.len(),
        d.since.len(),
        d.effects.len(),
    );

    s.push_str(
        "\n## Effect differences\n\n\
         The dangerous category: an approval prompt is driven by the classification, so a \n\
         mismatch means one of the two servers gets a decision made on the wrong information. \n\
         An empty section here is the expected state.\n\n",
    );
    if d.effects.is_empty() {
        s.push_str("None.\n");
    } else {
        s.push_str("| command | Redis | Valkey |\n|---|---|---|\n");
        for e in &d.effects {
            let _ = writeln!(s, "| `{}` | {} | {} |", e.name, e.redis, e.valkey);
        }
    }

    s.push_str(
        "\n## Commands only Redis has\n\n\
         Suggesting one of these to a Valkey server produces an error the user did not cause.\n\n",
    );
    write_list(&mut s, &d.redis_only);

    s.push_str(
        "\n## Commands only Valkey has\n\n\
         Hiding one of these from a Valkey user is the same failure in the other direction.\n\n",
    );
    write_list(&mut s, &d.valkey_only);

    s.push_str(
        "\n## Argument differences\n\n\
         Same command, different shape. Offering the wrong option produces a syntax error.\n\n",
    );
    if d.arguments.is_empty() {
        s.push_str("None.\n");
    } else {
        for a in &d.arguments {
            let _ = writeln!(s, "### `{}`\n", a.name);
            let _ = writeln!(s, "- Redis:  `{}`", a.redis);
            let _ = writeln!(s, "- Valkey: `{}`", a.valkey);
            if !a.redis_only_keywords.is_empty() {
                let _ = writeln!(
                    s,
                    "- Redis-only keywords: {}",
                    join_code(&a.redis_only_keywords)
                );
            }
            if !a.valkey_only_keywords.is_empty() {
                let _ = writeln!(
                    s,
                    "- Valkey-only keywords: {}",
                    join_code(&a.valkey_only_keywords)
                );
            }
            s.push('\n');
        }
    }

    s.push_str(
        "\n## `since` differences\n\n\
         Same command, introduced at different versions. Offering an option to a server too \n\
         old for it is an error the user did not cause.\n\n",
    );
    if d.since.is_empty() {
        s.push_str("None.\n");
    } else {
        s.push_str("| command | Redis | Valkey |\n|---|---|---|\n");
        for e in &d.since {
            let _ = writeln!(
                s,
                "| `{}` | {} | {} |",
                e.name,
                e.redis.as_deref().unwrap_or("—"),
                e.valkey.as_deref().unwrap_or("—")
            );
        }
    }
    s
}

fn write_list(s: &mut String, names: &[String]) {
    use std::fmt::Write as _;
    if names.is_empty() {
        s.push_str("None.\n");
        return;
    }
    for n in names {
        let _ = writeln!(s, "- `{n}`");
    }
}

fn join_code(v: &[String]) -> String {
    v.iter()
        .map(|k| format!("`{k}`"))
        .collect::<Vec<_>>()
        .join(", ")
}
